# Generated by Django 5.2.2 on 2025-08-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_goalssaving_colore'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='credentials_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='pin',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
